version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    command: ["npx", "expo", "start"]
