version: '3.8'  # Você pode usar a versão apropriada para o seu caso

services:
  teste:
    image: mysql:latest
    ports:
      - "3306:3306"  # Mapeamento de porta (host:container)
    volumes:
      - C:\Users\gusta\OneDrive\Desktop\database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=carro
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  frontend:
    build: ../../frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: ../../backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development


  container4:
    image: loadbalancer
    ports:
      - "90:80"
  
  container5:
    image: nginxc
    ports:
      - "80:80"

  container6:
    image: nginxc
    ports:
      - "81:80"